### ISSUE TITLE
XMLType specs failure due to PLS-00306

### ISSUE THREAD

**Issue by yahonda** [rsim/ruby-plsql#114]
These 3 specs got failed every time. Have not found the cause of them yet. Confirmed these specs are fine at trav

``` ruby
$ rake spec
/home/yahonda/.rbenv/versions/2.3.1/bin/ruby -I/home/yahonda/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.1/lib:/home/yahonda/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-support-3.5.0/lib /home/yahonda/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.1/exe/rspec --pattern spec/\*\*\{,/\*/\*\*\}/\*_spec.rb
............................................................................................................FFF..................................................................................................................................................................................................................................................................................................................................................

Failures:

  1) Parameter type mapping / Function or procedure with XMLType parameters should process XMLType parameters
     Failure/Error: @raw_cursor.exec(*bindvars)

     OCIError:
       ORA-06550: line 2, column 12:
       PLS-00306: wrong number or types of arguments in call to 'TEST_XMLTYPE'
       ORA-06550: line 2, column 1:
       PL/SQL: Statement ignored
     # stmt.c:243:in oci8lib_230.so
     # ./lib/plsql/oci_connection.rb:109:in `exec'
     # ./lib/plsql/procedure_call.rb:27:in `exec'
     # ./lib/plsql/procedure.rb:267:in `exec'
     # ./lib/plsql/schema.rb:185:in `method_missing'
     # ./spec/plsql/procedure_spec.rb:268:in `block (3 levels) in <top (required)>'

  2) Parameter type mapping / Function or procedure with XMLType parameters should work when passing a NULL value
     Failure/Error: @raw_cursor.exec(*bindvars)

     OCIError:
       ORA-06550: line 2, column 12:
       PLS-00306: wrong number or types of arguments in call to 'TEST_XMLTYPE'
       ORA-06550: line 2, column 1:
       PL/SQL: Statement ignored
     # stmt.c:243:in oci8lib_230.so
     # ./lib/plsql/oci_connection.rb:109:in `exec'
     # ./lib/plsql/procedure_call.rb:27:in `exec'
     # ./lib/plsql/procedure.rb:267:in `exec'
     # ./lib/plsql/schema.rb:185:in `method_missing'
     # ./spec/plsql/procedure_spec.rb:273:in `block (3 levels) in <top (required)>'

  3) Parameter type mapping / Function or procedure with XMLType parameters should assign input parameter to putput parameter
     Failure/Error: @raw_cursor.exec(*bindvars)

     OCIError:
       ORA-06550: line 2, column 1:
       PLS-00306: wrong number or types of arguments in call to 'TEST_XMLTYPE2'
       ORA-06550: line 2, column 1:
       PLS-00306: wrong number or types of arguments in call to 'TEST_XMLTYPE2'
       ORA-06550: line 2, column 1:
       PL/SQL: Statement ignored
     # stmt.c:243:in oci8lib_230.so
     # ./lib/plsql/oci_connection.rb:109:in `exec'
     # ./lib/plsql/procedure_call.rb:27:in `exec'
     # ./lib/plsql/procedure.rb:267:in `exec'
     # ./lib/plsql/schema.rb:185:in `method_missing'
     # ./spec/plsql/procedure_spec.rb:279:in `block (3 levels) in <top (required)>'

Finished in 47.72 seconds (files took 0.46588 seconds to load)
449 examples, 3 failures

Failed examples:

rspec ./spec/plsql/procedure_spec.rb:266 # Parameter type mapping / Function or procedure with XMLType parameters should process XMLType parameters
rspec ./spec/plsql/procedure_spec.rb:272 # Parameter type mapping / Function or procedure with XMLType parameters should work when passing a NULL value
rspec ./spec/plsql/procedure_spec.rb:277 # Parameter type mapping / Function or procedure with XMLType parameters should assign input parameter to putput parameter

/home/yahonda/.rbenv/versions/2.3.1/bin/ruby -I/home/yahonda/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.1/lib:/home/yahonda/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-support-3.5.0/lib /home/yahonda/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.1/exe/rspec --pattern spec/\*\*\{,/\*/\*\*\}/\*_spec.rb failed
$
```
- bundle show

``` ruby
$ bundle show
Gems included by the bundle:
  * activemodel (4.2.7)
  * activerecord (4.2.7)
  * activerecord-oracle_enhanced-adapter (1.6.7)
  * activesupport (4.2.7)
  * addressable (2.4.0)
  * arel (6.0.3)
  * builder (3.2.2)
  * bundler (1.12.5)
  * descendants_tracker (0.0.4)
  * diff-lcs (1.2.5)
  * docile (1.1.5)
  * faraday (0.9.2)
  * git (1.3.0)
  * github_api (0.14.4)
  * hashie (3.4.4)
  * highline (1.7.8)
  * i18n (0.7.0)
  * json (1.8.3)
  * juwelier (2.1.2)
  * jwt (1.5.4)
  * mini_portile2 (2.1.0)
  * minitest (5.9.0)
  * multi_json (1.12.1)
  * multi_xml (0.5.5)
  * multipart-post (2.0.0)
  * nokogiri (1.6.8)
  * oauth2 (1.0.0)
  * pkg-config (1.1.7)
  * rack (1.6.4)
  * rake (11.2.2)
  * rdoc (4.2.2)
  * rspec (3.5.0)
  * rspec-core (3.5.1)
  * rspec-expectations (3.5.0)
  * rspec-mocks (3.5.0)
  * rspec-support (3.5.0)
  * rspec_junit_formatter (0.2.3)
  * ruby-oci8 (2.2.2)
  * semver (1.0.1)
  * simplecov (0.12.0)
  * simplecov-html (0.10.0)
  * thread_safe (0.3.5)
  * tzinfo (1.2.2)
$
```
- Environment

```
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-linux]
Oracle Database 12c Enterprise Edition Release 12.1.0.2.0 - 64bit Production
```

**Comment by yahonda** [comment]
It does NOT reproduce with this environment:

```
Oracle Database 11g Express Edition Release 11.2.0.2.0 - 64bit Production
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-linux]
```

```ruby
$ bundle show
Gems included by the bundle:
  * activemodel (4.2.7)
  * activerecord (4.2.7)
  * activerecord-oracle_enhanced-adapter (1.6.7)
  * activesupport (4.2.7)
  * addressable (2.4.0)
  * arel (6.0.3)
  * builder (3.2.2)
  * bundler (1.12.5)
  * descendants_tracker (0.0.4)
  * diff-lcs (1.2.5)
  * docile (1.1.5)
  * faraday (0.9.2)
  * git (1.3.0)
  * github_api (0.14.4)
  * hashie (3.4.4)
  * highline (1.7.8)
  * i18n (0.7.0)
  * json (1.8.3)
  * juwelier (2.1.2)
  * jwt (1.5.4)
  * mini_portile2 (2.1.0)
  * minitest (5.9.0)
  * multi_json (1.12.1)
  * multi_xml (0.5.5)
  * multipart-post (2.0.0)
  * nokogiri (1.6.8)
  * oauth2 (1.0.0)
  * pkg-config (1.1.7)
  * rack (1.6.4)
  * rake (11.2.2)
  * rdoc (4.2.2)
  * rspec (3.5.0)
  * rspec-core (3.5.2)
  * rspec-expectations (3.5.0)
  * rspec-mocks (3.5.0)
  * rspec-support (3.5.0)
  * rspec_junit_formatter (0.2.3)
  * ruby-oci8 (2.2.2)
  * semver (1.0.1)
  * simplecov (0.12.0)
  * simplecov-html (0.10.0)
  * thread_safe (0.3.5)
  * tzinfo (1.2.2)$
```

**Comment by yahonda** [comment]
It still reproduces.

**Comment by yahonda** [comment]
Closing it. It still reproduces but have no extra time to investigate this. #157 has been merged to skip 3 related specs, which would reminds me or someone else this issue.
