### ISSUE TITLE
ALTER SESSION TIME_ZONE breaks test on certain ORA version <-> instant client version pairs

### ISSUE THREAD

**Issue by bbozo** [rsim/ruby-plsql#45]
From failing tests:

```
1.9.3-p286 :015 > conn = OCI8.new('hr', 'hr', "//#{DATABASE_HOST}:#{DATABASE_PORT}/#{DATABASE_NAME}")
 => #<OCI8:HR> 
1.9.3-p286 :016 > conn.select_one("SELECT current_timestamp from dual").first
 => 2013-02-23 15:13:34 +0100 
1.9.3-p286 :017 > conn.exec "alter session set time_zone = 'UTC'"
 => 0 
1.9.3-p286 :018 > conn.select_one("SELECT current_timestamp from dual").first
OCIError: ORA-01805: possible error in date/time operation
        from ocidatetime.c:119:in oci8lib_191.so
        from /home/bbozo/.rvm/gems/ruby-1.9.3-p286@ruby-plsql/gems/ruby-oci8-2.1.4/lib/oci8/datetime.rb:393:in `get'
        from /home/bbozo/.rvm/gems/ruby-1.9.3-p286@ruby-plsql/gems/ruby-oci8-2.1.4/lib/oci8/cursor.rb:538:in `get_data'
        from /home/bbozo/.rvm/gems/ruby-1.9.3-p286@ruby-plsql/gems/ruby-oci8-2.1.4/lib/oci8/cursor.rb:538:in `block in fetch_one_row_as_array'
        from /home/bbozo/.rvm/gems/ruby-1.9.3-p286@ruby-plsql/gems/ruby-oci8-2.1.4/lib/oci8/cursor.rb:537:in `collect'
        from /home/bbozo/.rvm/gems/ruby-1.9.3-p286@ruby-plsql/gems/ruby-oci8-2.1.4/lib/oci8/cursor.rb:537:in `fetch_one_row_as_array'
        from /home/bbozo/.rvm/gems/ruby-1.9.3-p286@ruby-plsql/gems/ruby-oci8-2.1.4/lib/oci8/cursor.rb:154:in `fetch'
        from /home/bbozo/.rvm/gems/ruby-1.9.3-p286@ruby-plsql/gems/ruby-oci8-2.1.4/lib/oci8/oci8.rb:326:in `select_one'
        from (irb):18
        from /home/bbozo/.rvm/rubies/ruby-1.9.3-p286/bin/irb:13:in `<main>'
```

"Fix" for me was to comment out the ENV['TZ'] setter in spec_helper.rb, this breaks other tests though. I digged out older mailing list entries from oracle_enhanced that link this to a ruby-oci8 error and a problem regarding a desync of time zone files between instant client and server (I run 11.2.0.2.0 server and 11.2.0.1.0 client)

I guess the solution is to use a different Instant Client version, perhaps someone here could know which one and include it in the docs?

I guess this would be something to have in mind in the oracle_enhanced gem too, especially for production purposes?

**Comment by jgebal** [comment]
This is pure Oracle Client issue.
I've had the same thing when running Instant Client 12.1.0.2 with Oracle XE 11.2.0.2
You need to make sure that you use Instant Client version that is aligned with Oracle Server.
This is related to the fact that Oracle uses static Timezone files that are updated between versions.

I have on my local machine (Windows)
```
C:\Users\Jacek>genezi -v
Client Shared Library 32-bit - 11.2.0.4.0

Windows NT Version V6.1 Service Pack 1
CPU                 : 8 - type 586, 4 Physical Cores
Process Affinity    : 0x0x00000000
Memory (Avail/Total): Ph:1159M/8180M, Ph+PgF:7855M/16359M, VA:1856M/2047M
Operating in Instant Client mode.
Small timezone file = timezone_14.dat
Large timezone file = timezlrg_14.dat
```

And on my Database server:
```
C:\Users\Jacek>sqlplus hr/hr@xe

SQL*Plus: Release 11.2.0.4.0 Production on Sun May 31 16:21:24 2015

Copyright (c) 1982, 2013, Oracle.  All rights reserved.


Connected to:
Oracle Database 11g Express Edition Release 11.2.0.2.0 - 64bit Production

SQL> select * from v$timezone_file;

FILENAME                VERSION
-------------------- ----------
timezlrg_14.dat              14

SQL>
```

This is not ruby-plsql related issue. [Stackoverflow on same issue for .NET](http://stackoverflow.com/questions/7678485/oracle-ora-01805-on-oracle-11g-database)

**Comment by jgebal** [comment]
@bbozo We could close this issue, if you dont mind.

**Comment by bbozo** [comment]
Sure

**Comment by jgebal** [comment]
Great.
Thanks
